apriltag:
  ros__parameters:
    family: 36h11
    size: 0.05
    image_transport: raw
    publish_tf: true
    debug: false
    pose_estimation_method: pnp
    tag:
      ids: [1]
      frames: ['tag36h11:1']
      sizes: [0.05]
